<html>
<head>
  <title>Cadastro de usuário</title>
</head>
<body>
  <h1>Cadastro de usuário</h1>
  <form action="sistema.php" method="post">
    <input type="hidden" name="cadastro" value="true">
    <label for="nome">Nome:</label>
    <input type="text" id="nome" name="nome" required><br>
    <label for="email">E-mail:</label>
    <input type="email" id="email" name="email" required><br>
    <label for="senha">Senha:</label>
    <input type="password" id="senha" name="senha" required><br>
    <input type="submit" value="Cadastrar">
  </form>
  <?php
  // Verificar se há uma mensagem de erro na variável $_GET['erro']
  if (isset($_GET['erro'])) {
    // Exibir a mensagem de erro em vermelho
    echo "<p style='color:red'>" . $_GET['erro'] . "</p>";
  }
  ?>
</body>
</html>
