<html>
<head>
  <title>Login de usuário</title>
</head>
<body>
  <h1>Login de usuário</h1>
  <form action="sistema.php" method="post">
    <input type="hidden" name="login" value="true">
    <label for="nome">Nome:</label>
    <input type="text" id="nome" name="nome" required><br>
    <label for="senha">Senha:</label>
    <input type="password" id="senha" name="senha" required><br>
    <input type="submit" value="Entrar">
  </form>
  <?php
  // Verificar se há uma mensagem de erro na variável $_GET['erro']
  if (isset($_GET['erro'])) {
    // Exibir a mensagem de erro em vermelho
    echo "<p style='color:red'>" . $_GET['erro'] . "</p>";
  }
  // Verificar se há uma mensagem de sucesso na variável $_GET['sucesso']
  if (isset($_GET['sucesso'])) {
    // Exibir a mensagem de sucesso em verde
    echo "<p style='color:green'>" . $_GET['sucesso'] . "</p>";
  }
  ?>
  <p>Ainda não tem uma conta? <a href="cadastro.html">Cadastre-se aqui</a></p>
</body>
</html>